server:
  port: 8089

spring:
  application:
    name: mail-service-seckill
  main:
    allow-bean-definition-overriding: true
  config:
    import: optional:nacos:mail-service-seckill.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: your-mysql-url
    username: your-mysql-username
    password: your-mysql-password
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: your-nacos-server-addr
      config:
        enabled: true
        server-addr: your-nacos-server-addr
        file-extension: yaml
        group: DEFAULT_GROUP
    sentinel:
      transport:
        dashboard: your-sentinel-dashboard-url
        port: 8720
      datasource:
        ds1:
          nacos:
            server-addr: your-nacos-server-addr
            data-id: ${spring.application.name}-sentinel-rules.json
            group-id: DEFAULT_GROUP
            rule-type: flow
            data-type: json
  data:
    redis:
      host: your-redis-host
      port: 6379
    lettuce:
      pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 2000ms

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.mail.api.*.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: your-rocketmq-name-server
  producer:
    group: seckill-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
