server:
  port: 8082

spring:
  application:
    name: mail-service-usr
  main:
    allow-bean-definition-overriding: true
  config:
    import: optional:nacos:mail-service-usr.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: your mysql url
    username: your mysql username
    password: your mysql password
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: your nacos server
      config:
        enabled: true
        server-addr: your nacos server
        file-extension: yaml
        group: DEFAULT_GROUP
  data:
    redis:
      host: your redis host
      port: 6379


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.mail.api.*.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"