server:
  port: 8086

spring:
  application:
    name: mail-service-order
  main:
    allow-bean-definition-overriding: true
  config:
    import: optional:nacos:mail-service-order.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: your-mysql-url
    username:  your-mysql-username
    password:  your-mysql-password
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: your-nacos-server-addr
      config:
        enabled: true
        server-addr: your-nacos-server-addr
        file-extension: yaml
        group: DEFAULT_GROUP
  data:
    redis:
      host: your-redis-host
      port: 6379


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.mail.*.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: your-rocketmq-name-server
  producer:
    group: your-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"